### ISSUE TITLE
Table to Polygon - does not accept a csv file as Input Table

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#104]
@topowright @mfunk 

Conversion Toolset - **Table to Polygon** - does not accept a csv file as Input Table.  The sample file was created by copying the TableToPolyline.csv.  If Model opened for editing and saved w/o making changes, the parameters are rearranged (to be logged in seperate issue).

Tested using Pro 1.3 build 5792

![image](https://cloud.githubusercontent.com/assets/6842145/15719855/d57a8d7c-27ff-11e6-97d7-4a2d75a98dee.png)

**Comment by pshowalter** [comment]
Redundant issue: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/76

**Comment by mfunk** [comment]
Not sure this one is related to #76  as that problem is fixed for the Pro version of the tool. However this is showing a problem with Model Builder in that the link to the **Polyline To Polygon** script tool is broken, and there is no way to fix it (that is, reset it's correct source location).

![image](https://cloud.githubusercontent.com/assets/3093182/15787387/fffeb244-2976-11e6-9eae-c6c33e9094f3.png)

In ArcMap Model Builder would allow us to browse to the correct location of the ***Polyline To Polygon** tool.

**Comment by mfunk** [comment]
This is also affecting **Table To Ellipse** (link to *Polyline To Polygon* is broken) and **Convert Coordinates** (link to *sourceCC* is broken).

**Comment by mfunk** [comment]
This is what we see in ArcMap when the link to a tool is broken..

![image](https://cloud.githubusercontent.com/assets/3093182/15787833/457178e6-2979-11e6-997e-524c250326da.png)

**Comment by jmccausland** [comment]
I noticed I would receive these errors if I sync'd from github WHILE I had ArcMap or Pro open with the toolboxes, etc.  Closing all Arc-products and doing a hard reset fixed them.

**Comment by jmccausland** [comment]
Looks like there's been some core changes in Pro that breaks the animated flash that we created.

**Comment by mfunk** [comment]
Fixed in #146

**Comment by NatalieCampos** [comment]
fix verified
