### ISSUE TITLE
In Pro output sightlines symbology is reversed

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#190]
## Expected Behavior
sight lines should be symbolized so that visible [1] is a white line and non-visible [0] is a black line

## Current Behavior
symbology is reversed, visible [1] is a black line and non-visible [0] is a white line

## Possible Solution
reverse symbology in the lyrx file for output sightlines

**Comment by mfunk** [comment]
Currently we get this with the test data (LLOS_Observers and LLOS_Targets) running LLOS in ArcMap 10.3. The results here are correct and what we are expecting. Note that there are three observers that can see one of the targets, the observers are connected to the target by white line and the target is labeled with the number 3.

![image](https://cloud.githubusercontent.com/assets/3093182/21231108/ef53fa58-c29b-11e6-9dd7-6b61ef6fb770.png)

In Pro 1.2, using the same inputs, we get the following:

![image](https://cloud.githubusercontent.com/assets/3093182/21231284/964bd1dc-c29c-11e6-9bb6-e4992f9e2c87.png)

Forget that the TOC isn't labeled properly (issues with Pro itself) but the colors for the output sight lines is backwards.

**Comment by mfunk** [comment]
Here is the expected results (symbolology updated.... again).

![image](https://cloud.githubusercontent.com/assets/3093182/21231747/34b45776-c29e-11e6-8580-f5cce7c3b783.png)

However due to Pro defects the TOC labels are wrong, and the output Targets are not labeled either.

![image](https://cloud.githubusercontent.com/assets/3093182/21232141/806af4e4-c29f-11e6-8d1e-c4d0465214ab.png)

The Target labeling is due to:
BUG-000101471 "Geoprocessing tools in ArcGIS Pro do not honor output layer file (.lyrx) labels for tool results."

The TOC labels are a different bug altogether. Will have to log this one separately.

**Comment by dfoll** [comment]
this is an issue with Pro
