### ISSUE TITLE
Find Local Peaks tool has an undocumented upper limit of 10 for the # of peaks

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#217]
The find the local peaks tools has an undocumented upper limit of 10 for the number of peaks dialog. A value greater than 10 causes the tool to crash.  A value less than 10 is fine.  This seems like an arbitrary limit.   Please document the upper limit in the tool help or remove the upper limit within the code.  See screen capture below.  

## Current Behavior
Tool fails if number of peaks is greater than 10

## Possible Solution
Remove the upper limit or clearly document the upper limit. 
## Context
This was reported by Thomas Humber in Training Services.

**Comment by adgiles** [comment]
I have not found any reference to a upper limit of 10 peaks in the code and I could not replicate on the sample data. I stepped up the testing from 10 to a hundred and it ran fine. I tried again with 1000 peaks and it failed.

On investigation it appears that if the number of peaks (inverted sink holes) within the elevation area of input is less than the Number of Peaks determined by the user, it will throw an error (due to trying to access an array value greater than the array length).

The solution was to set the number of peaks to the number of sink holes (if less than the user input) and inform the user that this has been done.

This got me thinking what would happen if no sinks holes are found (a very small or flat AOI). As I expected this also caused the code to error, so I have also added a error check for this.

Please can somebody verify once PR #218 has been merged

**Comment by NatalieCampos** [comment]
@adgiles this is the error thrown by the user

Number Of Peaks	25
Input Surface	C:\EsriTraining\PROD\Viewshed\Asadabad.gdb\DTED_Clip
Output Peak Features	C:\EsriTraining\PROD\Viewshed\Asadabad.gdb\peaks_test

Messages	
Start Time: Wednesday, May 17, 2017 11:04:50 AM
Running script FindLocalPeaks...
Using WGS_1984_UTM_Zone_42N for analysis.
Clipping DTED_Clip to area tempAreaFeatures...
Inverting clipped surface...
_getRasterMinMax min=808.0, max=1834.0
Finding inverted sinks...
Extracting elevation values from C:\EsriTraining\PROD\Viewshed\Asadabad.gdb\DTED_Clip...
PYTHON ERRORS:Traceback info:  File "C:\Users\thom7420\Desktop\military-tools-geoprocessing-toolbox-dev\toolboxes\scripts\VisibilityUtilities.py", line 1029, in findLocalPeaks    cutoffValue = uniqueElevationList[int(inputNumberOfPeaks) - 1]Error Info:list index out of range
ArcPy ERRORS:Start Time: Wednesday, May 17, 2017 11:04:58 AMSucceeded at Wednesday, May 17, 2017 11:04:58 AM (Elapsed Time: 0.31 seconds)
Removing intermediate datasets...
Removing: C:\EsriTraining\PROD_Workflows\PROD_Workflows.gdb\tempAreaFeatures
Removing: C:\EsriTraining\PROD_Workflows\PROD_Workflows.gdb\clipSurface
Removing: C:\EsriTraining\PROD_Workflows\PROD_Workflows.gdb\invertedSinks
Removing: C:\EsriTraining\PROD_Workflows\PROD_Workflows.gdb\pointSinks
Removing: C:\EsriTraining\PROD_Workflows\PROD_Workflows.gdb\sinkValues
Done
Completed script FindLocalPeaks...
Failed to execute (FindLocalPeaks).
Failed at Wednesday, May 17, 2017 11:05:08 AM (Elapsed Time: 18.04 seconds)

**Comment by NatalieCampos** [comment]
Original data was tested and now the tool allows for greater than 10 peaks.  closing issue.

**Comment by NatalieCampos** [comment]
@adgiles tested this with several datasets  including the original datasetthat brought up the issue.  The fixed you provided does allow for over 10 peaks... however the tool seem to provided as output the value in the Number of Peaks dialog plus one.  For example, my Number of Peak = 15, as seen below.

![image](https://cloud.githubusercontent.com/assets/5116835/26226161/8ded040e-3bdf-11e7-94ac-795b81092218.png)
However, I am returned 16 total peaks.
![image](https://cloud.githubusercontent.com/assets/5116835/26226175/a5de6e7c-3bdf-11e7-803c-38eb51d568e1.png)

The tool should correctly honor the value in the Number of Peaks dialog.

**Comment by NatalieCampos** [comment]
@thumber1776

**Comment by adgiles** [comment]
see #221 ready to verify

**Comment by NatalieCampos** [comment]
verified
