### ISSUE TITLE
Create GRG from Point - tool works but output not symbolized with LYR file

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#361]
The Create GRG from Point tool from Military Tools build 73 runs correctly, but the output that is added does not have the correct symbology.
![image](https://user-images.githubusercontent.com/3801392/42052663-40d8874a-7ac4-11e8-8d3a-1979d99c5d98.png)

## Expected Behavior
Output should get symbology from correct LYR file.

## Current Behavior
Tool runs, GRG polys created and numbered, but no symbology or labeling applied.

## Possible Solution
Replace LYR file.

## Steps to Reproduce (for bugs)
1. Create GRG from Point tool
2. Digitize a point
3. Accept defaults (I set a rotation of 14 degrees for fun)
4. Run
Result: Tool runs, GRG polys created and numbered, but no symbology or labeling applied.

## Context
Output looks wrong

## Your Environment
Military Tools build 73
ArcMap (10.3.1 - Advanced)

**Comment by BobBooth** [comment]
@dfoll - found this other issue while testing Build 73 on ArcMap.

**Comment by BobBooth** [comment]
Also, when I run this in Pro, I see in the messaging:
"... 
Merging temporary, rotated dataset with output
Do not apply symbology it will be done in the next task step
Completed script Create GRG From Point...
..."

Isn't this a pre-2.2 version of the code?  

@csmoore / @kgonzago  does this seem like an older version of the code?

**Comment by csmoore** [comment]
@BobBooth - I do see that a layer file got dropped in the reorg: 

GRG.lyr was here:
https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/pre-reorg/toolboxes/layers

But no longer here: 
https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/Geoprocessing/layers

I'll run a pre and post - diff again since I missed this the last time

**Comment by csmoore** [comment]
I believe this was caused by the missing GRG.lyr file in the ArcMap set of files/folder here: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/Geoprocessing/layers

This seems to work now in ArcMap:

![image](https://user-images.githubusercontent.com/3090809/42331422-5e66b2a8-8043-11e8-82a0-459962e1a314.png)

**Comment by BobBooth** [comment]
I am attempting to test, but in order to do so, I need a rebuild of the MT conda package.
I have started looking at the Utils folder (https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/utils) and am trying to install conda-build on my machine (no luck so far).
@topowright - if you can kick off another conda-package build (or point me to instructions on how to do that), I'd appreciate it.

**Comment by lfunkhouser** [comment]
@BobBooth this issue will be on hold until another conda package is available.

**Comment by BobBooth** [comment]
I was mistaken about needing a rebuilt conda package. The tool is working correctly in ArcMap 10.3.1 from the current (released) download item.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/ef0a91ea-febb-4a17-93d8-70154aaa0ef2)
It is also working in Pro (from the conda package installed tool).
